add option to disable noatime on entire zfs pool

diff --git a/tools/zfsinstall b/tools/zfsinstall
--- a/tools/zfsinstall
+++ b/tools/zfsinstall
@@ -7,7 +7,7 @@
 FS_LIST="var tmp"
 
 usage() {
-	echo "Usage: $0 [-h] -d geom_provider [-d geom_provider ...] -u dist_url [-r mirror|raidz] [-m mount_point] [-p zfs_pool_name] [-V zfs_pool_version] [-s swap_partition_size] [-z zfs_partition_size] [-c] [-l] [-4]"
+	echo "Usage: $0 [-h] -d geom_provider [-d geom_provider ...] -u dist_url [-r mirror|raidz] [-m mount_point] [-p zfs_pool_name] [-V zfs_pool_version] [-s swap_partition_size] [-z zfs_partition_size] [-c] [-l] [-4] [-n]"
 }
 
 help() {
@@ -25,6 +25,7 @@ help() {
 	echo "-c                : enable lzjb compression for all datasets"
 	echo "-l                : use legacy mounts (via fstab) instead of ZFS mounts"
 	echo "-4                : use fletcher4 as default checksum algorithm"
+	echo "-n                : disable zfs access time updates (noatime)"
 	echo; echo "Examples:"
 	echo "Install on a single drive with 2GB swap:"
 	echo "$0 -u /path/to/release -d da0 -s 2G"
@@ -36,7 +37,7 @@ help() {
 	echo "You can enable all swap partitions and/or make a gmirror-ed swap later."
 }
 
-while getopts d:u:t:r:p:s:z:m:V:hcl4 o; do
+while getopts d:u:t:r:p:s:z:m:V:hcl4n o; do
 	case "$o" in
         	d) DEVS="$DEVS ${OPTARG##/dev/}" ;;
 		u) URL="${OPTARG}" ;;
@@ -50,6 +51,7 @@ while getopts d:u:t:r:p:s:z:m:V:hcl4 o; do
 		c) LZJB=1 ;;
 		l) LEGACY=1 ;;
 		4) FLETCHER=1 ;;
+		n) NOATIME=1 ;;
 		h) help; exit 1;;
 		[?]) usage; exit 1;;
 esac
@@ -276,6 +278,15 @@ fi
 if [ "${LZJB}" = "1" ]; then
 	echo -n "Setting default compression to lzjb for ${POOL} ..."
 	if ! /sbin/zfs set compression=lzjb ${POOL} > /dev/null 2> /dev/null; then
+		echo " error"
+		exit 1
+	fi
+	echo " done"
+fi
+
+if [ "${NOATIME}" = "1" ]; then
+	echo -n "Disabling atime updates for ${POOL} ..."
+	if ! /sbin/zfs set atime=off ${POOL} > /dev/null 2> /dev/null; then
 		echo " error"
 		exit 1
 	fi
